name: Pylint
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} #for granting permission
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Analysing the code with linter
        run: |
          python .github/workflows/linter.py
      - name: Commit and push
        run: |
          git config --global user.name actions-user
          git config --global user.email 'actions@github.com'
          git add .
          git commit -m "Done"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Verifying linting results
        run: |
          cat app/api/routes.py
